// <auto-generated />
using System;
using Booking.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booking.Service.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260414184939_InitialBookingPersistence")]
    partial class InitialBookingPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EventId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "CreatedAtUtc", "Id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.BookingReservedSeatEntity", b =>
                {
                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("BookingId", "SeatNumber");

                    b.ToTable("booking_reserved_seats", (string)null);
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("StartsAtUtc", "Id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.EventReservedSeatEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("EventId", "SeatNumber");

                    b.ToTable("event_reserved_seats", (string)null);
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.EventSeatEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("EventId", "SeatNumber");

                    b.ToTable("event_seats", (string)null);
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.BookingReservedSeatEntity", b =>
                {
                    b.HasOne("Booking.Service.Infrastructure.Persistence.Models.BookingEntity", "Booking")
                        .WithMany("ReservedSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.EventReservedSeatEntity", b =>
                {
                    b.HasOne("Booking.Service.Infrastructure.Persistence.Models.EventEntity", "Event")
                        .WithMany("ReservedSeats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.EventSeatEntity", b =>
                {
                    b.HasOne("Booking.Service.Infrastructure.Persistence.Models.EventEntity", "Event")
                        .WithMany("Seats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.BookingEntity", b =>
                {
                    b.Navigation("ReservedSeats");
                });

            modelBuilder.Entity("Booking.Service.Infrastructure.Persistence.Models.EventEntity", b =>
                {
                    b.Navigation("ReservedSeats");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
