<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Booking.Service.Api\Booking.Service.Api.csproj" />
    <ProjectReference Include="..\..\src\Booking.Service.Application\Booking.Service.Application.csproj" />
    <ProjectReference Include="..\..\src\Booking.Service.Infrastructure\Booking.Service.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Booking.Service.Domain\Booking.Service.Domain.csproj" />
    <PackageReference Include="EventHub.BuildingBlocks" />
    <PackageReference Include="EventHub.Contracts" />
  </ItemGroup>

</Project>